// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moxy.Data;

namespace Moxy.Data.Migrations
{
    [DbContext(typeof(MoxyDbContext))]
    partial class MoxyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Moxy.Data.Domain.CmsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("ArtContent")
                        .HasColumnName("art_content");

                    b.Property<string>("ArtDesc")
                        .HasColumnName("art_desc")
                        .HasMaxLength(300);

                    b.Property<string>("ArtTitle")
                        .HasColumnName("art_title")
                        .HasMaxLength(100);

                    b.Property<int?>("CategoryId")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnName("deleted_by")
                        .HasMaxLength(100);

                    b.Property<string>("DisplayCode")
                        .HasColumnName("display_code")
                        .HasMaxLength(100);

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRelease")
                        .HasColumnName("is_release");

                    b.Property<DateTime?>("ReleaseTime")
                        .HasColumnName("release_time");

                    b.Property<string>("Tags")
                        .HasColumnName("tags")
                        .HasMaxLength(300);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnName("updated_by")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("cms_article");
                });

            modelBuilder.Entity("Moxy.Data.Domain.CmsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("CategoryDesc")
                        .HasColumnName("category_desc")
                        .HasMaxLength(300);

                    b.Property<string>("CategoryName")
                        .HasColumnName("category_name")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("cms_category");
                });

            modelBuilder.Entity("Moxy.Data.Domain.SysAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("AdminKey")
                        .HasColumnName("admin_key")
                        .HasMaxLength(100);

                    b.Property<string>("AdminName")
                        .HasColumnName("admin_name")
                        .HasMaxLength(100);

                    b.Property<string>("AdminPwd")
                        .HasColumnName("admin_pwd")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnName("created_by")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DeletedBy")
                        .HasColumnName("deleted_by")
                        .HasMaxLength(100);

                    b.Property<bool?>("IsDeleted")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEnable")
                        .HasColumnName("is_enable");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnName("updated_by")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("sys_admin");
                });

            modelBuilder.Entity("Moxy.Data.Domain.SysConfig", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("code")
                        .HasMaxLength(200);

                    b.Property<string>("Value")
                        .HasColumnName("value");

                    b.HasKey("Code");

                    b.ToTable("sys_config");
                });
#pragma warning restore 612, 618
        }
    }
}
